### PR TITLE
Feature Leaderboard system

### LINKED ISSUE #2: Feat: Leaderboard system for high scores
### Describe the feature

# Feature
Added a leaderboard system for high scores to the Air Hockey game. Also the leaderboard will be updated after each game, and players can view it from the start screen or the end screen. The leaderboard data will be stored in a JSON file, so it persists between game sessions.

Should I move forward with creating a PR?

### Add ScreenShots

Screenshot 2024-10-14 at 7 16 09 PM
Screenshot 2024-10-14 at 7 30 32 PM

### Record

- [X] I agree to follow this project's Contributing.md
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by yazdanhaider**
## Related Issue
Fixes #2 

## Description
Added a leaderboard system for high scores to the Air Hockey game. Also the leaderboard will be updated after each game, and players can view it from the start screen or the end screen. The leaderboard data will be stored in a JSON file, so it persists between game sessions.

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
Screenshot 2024-10-14 at 7 16 09 PM
Screenshot 2024-10-14 at 7 30 32 PM

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by yazdanhaider** [comment]
Hey @Ojas-Arora, I have successfully added the leaderboard system feature and have checked it manually. Please proceed with the merge!!

**Review by Ojas-Arora — APPROVED** [review]
Looks Good

**Comment by Ojas-Arora** [comment]
@yazdanhaider Add your details in the CONTRIBUTORS.md file and follow the Maintainers of the repo.

**Comment by yazdanhaider** [comment]
> @yazdanhaider Add your details in the CONTRIBUTORS.md file and follow the Maintainers of the repo.

Updated @Ojas-Arora.

**Pull request merged**
